import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Paper, Center, Text } from '@mantine/core'
// import { ArticleCardImage } from './ArticleCardImage'
import {  HeaderResponsive } from './HeaderResponsive'
// import { HeaderMenu } from './HeaderMenu'
import  HeroContentLeft  from './HeroContentLeft'
import  {HeroImageRight}  from './HeroImageRight'
// import {  ArticlesCardsGrid } from './ArticlesCardsGrid'
import Second_Card_Grid from './Second_Card_Grid'
import Cards from './Cards'
// import Recently_Added_Card from './NewCArd'
import FooterResponsive from './FooterResponsive'
import NewCard from './NewCArd'


// import FooterLinks from './FooterLinks'
 

const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper shadow="xs" p="md" >
      <HeaderResponsive links={[
         {
          "link": "/about",
          "label": "Features"
        },
        {
          "link": "/pricing",
          "label": "Pricing"
        },
        {
          "link": "/learn",
          "label": "Learn"
        },
        {
          "link": "/community",
          "label": "Community"
        }
      ]} />

      {/* <HeaderMenu links={[
        {
          "link": "/about",
          "label": "Features"
        },
        {
          "link": "#1",
          "label": "Learn",
          "links": [
            {
              "link": "/docs",
              "label": "Documentation"
            },
            {
              "link": "/resources",
              "label": "Resources"
            },
            {
              "link": "/community",
              "label": "Community"
            },
            {
              "link": "/blog",
              "label": "Blog"
            }
          ]
        },
        {
          "link": "/about",
          "label": "About"
        },
        {
          "link": "/pricing",
          "label": "Pricing"
        },
        {
          "link": "#2",
          "label": "Support",
          "links": [
            {
              "link": "/faq",
              "label": "FAQ"
            },
            {
              "link": "/demo",
              "label": "Book a demo"
            },
            {
              "link": "/forums",
              "label": "Forums"
            }
          ]
        }
      ]}/> */}
    <HeroContentLeft/>
      {/* <div style={{marginTop: 30 }}>
      <h1 style={{textAlign:'center'}}>We are Available in many</h1>
      <h1 style={{textAlign:'center'}}>Well-known countries</h1>

      </div> */}
      <Cards/>
   {/* <div style={{display:'flex', justifyContent:'center'}}>
   <ArticleCardImage image={'https://images.unsplash.com/photo-1498174979972-c9de7e6a93d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80'} title={'America'} />
     <ArticleCardImage image={'https://images.unsplash.com/photo-1498174979972-c9de7e6a93d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80'} title={'America'} />
     <ArticleCardImage image={'https://images.unsplash.com/photo-1498174979972-c9de7e6a93d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80'} title={'America'} />
     <ArticleCardImage image={'https://images.unsplash.com/photo-1498174979972-c9de7e6a93d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80'} title={'America'} />
    
   </div> */}
{/* <div style={{marginTop:'30px'}}>
<h1 style={{marginLeft:'65px'}}>Recently Added</h1>
</div> */}
   {/* <ArticlesCardsGrid/> */}
   {/* <Second_Card_Grid/> */}
   <NewCard/>
   <HeroImageRight/>
   
   <FooterResponsive/>
   
   {/* <FooterLinks/> */}
   </Paper>
    </>
  )
}


